M48
; DRILL file {KiCad (6.0.4)} date Sat Mar 19 22:36:42 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-19T22:36:42+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X148.666Y-84.044
X178.384Y-99.284
T2
X98.425Y-83.185
X98.425Y-126.365
X182.88Y-125.095
X198.12Y-83.82
T0
M30
